export const portfolioData = [
  { id: 1, category: "Royal Wedding", featuredImage: "/portfolio/01.jpg" },
  { id: 2, category: "Beach Wedding", featuredImage: "/portfolio/02.jpg" },
  { id: 3, category: "Intimate Union", featuredImage: "/portfolio/03.jpg" },
  { id: 4, category: "Editorial Portraits", featuredImage: "/portfolio/04.jpg" },
  { id: 5, category: "Royal Wedding", featuredImage: "/portfolio/05.jpg" },
  { id: 6, category: "Beach Wedding", featuredImage: "/portfolio/06.jpg" },
  { id: 7, category: "Intimate Union", featuredImage: "/portfolio/07.jpg" },
  { id: 8, category: "Editorial Portraits", featuredImage: "/portfolio/08.jpg" },
  { id: 9, category: "Royal Wedding", featuredImage: "/portfolio/09.jpg" },
  { id: 10, category: "Beach Wedding", featuredImage: "/portfolio/10.jpg" },
  { id: 11, category: "Intimate Union", featuredImage: "/portfolio/11.jpg" },
  { id: 12, category: "Editorial Portraits", featuredImage: "/portfolio/12.jpg" },
  { id: 13, category: "Royal Wedding", featuredImage: "/portfolio/13.jpg" },
  { id: 14, category: "Beach Wedding", featuredImage: "/portfolio/14.jpg" },
  { id: 15, category: "Intimate Union", featuredImage: "/portfolio/15.jpg" },
  { id: 16, category: "Editorial Portraits", featuredImage: "/portfolio/16.jpg" },
  { id: 17, category: "Royal Wedding", featuredImage: "/portfolio/17.jpg" },
  { id: 18, category: "Beach Wedding", featuredImage: "/portfolio/18.jpg" },
  { id: 19, category: "Intimate Union", featuredImage: "/portfolio/19.jpg" },
  { id: 20, category: "Editorial Portraits", featuredImage: "/portfolio/20.jpg" },
  { id: 21, category: "Royal Wedding", featuredImage: "/portfolio/21.jpg" },
  { id: 22, category: "Beach Wedding", featuredImage: "/portfolio/22.jpg" },
  { id: 23, category: "Intimate Union", featuredImage: "/portfolio/23.jpg" },
  { id: 24, category: "Editorial Portraits", featuredImage: "/portfolio/24.jpg" },
  { id: 25, category: "Royal Wedding", featuredImage: "/portfolio/25.jpg" },
  { id: 26, category: "Beach Wedding", featuredImage: "/portfolio/26.jpg" },
  { id: 27, category: "Intimate Union", featuredImage: "/portfolio/27.jpg" },
  { id: 28, category: "Editorial Portraits", featuredImage: "/portfolio/28.jpg" },
  { id: 29, category: "Royal Wedding", featuredImage: "/portfolio/29.jpg" },
  { id: 30, category: "Beach Wedding", featuredImage: "/portfolio/30.jpg" },
  { id: 31, category: "Intimate Union", featuredImage: "/portfolio/31.jpg" },
  { id: 32, category: "Editorial Portraits", featuredImage: "/portfolio/32.jpg" },
  { id: 33, category: "Royal Wedding", featuredImage: "/portfolio/33.jpg" },
  { id: 34, category: "Beach Wedding", featuredImage: "/portfolio/34.jpg" },
  { id: 35, category: "Intimate Union", featuredImage: "/portfolio/35.jpg" },
  { id: 36, category: "Editorial Portraits", featuredImage: "/portfolio/36.jpg" },
  { id: 37, category: "Royal Wedding", featuredImage: "/portfolio/37.jpg" },
  { id: 38, category: "Beach Wedding", featuredImage: "/portfolio/38.jpg" }
];

export const categories = [
  "All Stories",
  "Royal Wedding",
  "Beach Wedding",
  "Intimate Union",
  "Editorial Portraits"
];